#!/bin/bash
# Author: dmatosl <danielmatos.lima@gmail.com>
# Description: virsh cmd running inside a docker container

set -euo pipefail

VIRT_MANAGER_DIR=${VIRT_MANAGER_DIR:-$PWD/.config}

docker run --rm -it \
  -e DISPLAY=${HOSTNAME}:0 \
  -v ~/.ssh/id_rsa:/root/.ssh/id_rsa \
  dmatosl/virt-manager:0.0.1 \
    /usr/bin/virsh --connect=qemu+ssh://daniel@iron.lan/system $@
