#!/bin/bash
# Author: dmatosl <danielmatos.lima@gmail.com>
# Description: virsh cmd running inside a docker container

set -euo pipefail

VIRT_MANAGER_DIR=${VIRT_MANAGER_DIR:-$PWD/.config}
VIRT_MANAGER_IMAGE="dmatosl/docker-virt-manager:latest"

docker run --rm -it \
  -e DISPLAY=${HOSTNAME}:0 \
  -v ~/.ssh:/root/.ssh \
  ${VIRT_MANAGER_IMAGE} \
    /usr/bin/virsh --connect=qemu+ssh://daniel@iron.lan/system $@
