#!/bin/bash
# Author: dmatosl <danielmatos.lima@gmail.com>
# Description: virt-manager cmd running inside a docker container
# Depends: socat + xQuartz + Docker

set -euo pipefail

VIRT_MANAGER_DIR=${VIRT_MANAGER_DIR:-$PWD/.config}
VIRT_MANAGER_IMAGE="dmatosl/docker-virt-manager:latest"

socat TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\" & 

docker run --rm \
  -e DISPLAY=${HOSTNAME}:0 \
  -v ~/.ssh:/root/.ssh \
  -v ${VIRT_MANAGER_DIR}:/root/.config/dconf \
  $@ \
  dmatosl/docker-virt-manager:latest
